/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JButton;

/**
 *
 * @author kovacs.d.csaba
 */
public class Dolgozat extends javax.swing.JFrame {

    /**
     * Creates new form Dolgozat
     */
    public Dolgozat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BBalPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        BJobbPanel = new javax.swing.JPanel();
        BJobbCheck1 = new javax.swing.JCheckBox();
        BJobbTextField1 = new javax.swing.JTextField();
        BJobbLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUI- OOP 1.Dolgozat");
        setPreferredSize(new java.awt.Dimension(410, 350));

        BBalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Pin kód"));
        BBalPanel.setToolTipText("");
        BBalPanel.setPreferredSize(new java.awt.Dimension(410, 350));
        BBalPanel.setLayout(new java.awt.GridLayout(0, 3));

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BBalPanel.add(jButton1);

        jButton2.setText("2");
        BBalPanel.add(jButton2);

        jButton3.setText("3");
        BBalPanel.add(jButton3);

        jButton4.setText("4");
        BBalPanel.add(jButton4);

        jButton5.setText("5");
        BBalPanel.add(jButton5);

        jButton6.setText("6");
        BBalPanel.add(jButton6);

        jButton7.setText("7");
        BBalPanel.add(jButton7);

        jButton8.setText("8");
        BBalPanel.add(jButton8);

        jButton9.setText("9");
        BBalPanel.add(jButton9);

        jButton10.setText("0");
        BBalPanel.add(jButton10);

        BJobbPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Beállítás")));
        BJobbPanel.setPreferredSize(new java.awt.Dimension(410, 350));

        BJobbCheck1.setText("Kever");
        BJobbCheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJobbCheck1ActionPerformed(evt);
            }
        });

        BJobbLabel1.setText("Kód:");

        javax.swing.GroupLayout BJobbPanelLayout = new javax.swing.GroupLayout(BJobbPanel);
        BJobbPanel.setLayout(BJobbPanelLayout);
        BJobbPanelLayout.setHorizontalGroup(
            BJobbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BJobbPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BJobbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BJobbTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addGroup(BJobbPanelLayout.createSequentialGroup()
                        .addGroup(BJobbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BJobbCheck1)
                            .addComponent(BJobbLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        BJobbPanelLayout.setVerticalGroup(
            BJobbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BJobbPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BJobbCheck1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(BJobbLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BJobbTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BBalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BJobbPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BJobbPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bejelentkezés", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Játék", jPanel3);

        jMenu1.setText("Program");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Játék elrendezése");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BJobbCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BJobbCheck1ActionPerformed
        if (BJobbCheck1.isSelected()) {

        }
    }//GEN-LAST:event_BJobbCheck1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        gombRandomizal();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dolgozat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dolgozat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dolgozat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dolgozat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dolgozat().setVisible(true);
            }
        });
    }

    private void GombLetrehoz() {

    }

    private void gombRandomizal() {
        ArrayList<JButton> Gombok = new ArrayList<JButton>();
        ArrayList<JButton> Eredeti = new ArrayList<>();
        Gombok.add(jButton1);
        Gombok.add(jButton2);
        Gombok.add(jButton3);
        Gombok.add(jButton4);
        Gombok.add(jButton5);
        Gombok.add(jButton6);
        Gombok.add(jButton7);
        Gombok.add(jButton8);
        Gombok.add(jButton9);
        Gombok.add(jButton10);

        Eredeti = (ArrayList) Gombok.clone();
        Collections.shuffle(Gombok);
        jButton1
        
        
        
//        for (int i = 0; i < Gombok.size(); i++) {
//            System.out.println(Gombok.get(i).getText());
//        }
//        System.out.println("-----------------------");
//        for (int i = 0; i < 10; i++) {
//            System.out.println(Gombok.get(i).getText());
//
//            jButton1.setText(Gombok.get(i).getText());
//
//        }
//        System.out.println("-----------------------");
//        System.out.println("-----------------------");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BBalPanel;
    private javax.swing.JCheckBox BJobbCheck1;
    private javax.swing.JLabel BJobbLabel1;
    private javax.swing.JPanel BJobbPanel;
    private javax.swing.JTextField BJobbTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
